spring:
  data:
    mongodb:
      uri: mongodb+srv://prash:Welcome123@mycluster.kngtitw.mongodb.net/demo
      database: demo

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG